#! /usr/bin/env bash

# Print an error message and exit.
panic()
{
	echo "ERROR: $@"
	exit 1
}

# Get the directory in which the currently running script is located.
cmd_dir=$(dirname "$0") || panic "cannot determine command directory"

black_navy_war_program="$cmd_dir/black_navy_war"

echo "Running black_navy_war program"
$black_navy_war_program || panic "black_navy_war program failed"